\ -*-forth-*-
\ i386 machine
\   pure stack (TOS not cached)
\ ESP: pstack
\ EBP: rstack
\ ESI: IP
\ EAX: W
\ EDI: U
\ $NEXT: - sort of, EAX points to CFA
\   lodsl
\   jmp *(%eax)

include" lib/store.fs"
include" lib/fetch.fs"
include" lib/c-store.fs"
include" lib/c-fetch.fs"
include" lib/rp-store.fs"
include" lib/sp-store.fs"
include" lib/rp-fetch.fs"
include" lib/sp-fetch.fs"
include" lib/dash-rot.fs"
include" lib/to-r.fs"
include" lib/drop.fs"
include" lib/dup.fs"
include" lib/over.fs"
include" lib/pick.fs"
include" lib/r-from.fs"
include" lib/r-fetch.fs"
include" lib/rot.fs"
include" lib/swap.fs"
include" lib/paren-zero-branch.fs"
include" lib/paren-branch.fs"
include" lib/paren-dolit.fs"
include" lib/paren-s-quote.fs"
include" lib/execute.fs"
include" lib/exit.fs"
include" lib/paren-question-do.fs"
include" lib/paren-plus-loop.fs"
include" lib/paren-do.fs"
include" lib/paren-leave.fs"
include" lib/paren-loop.fs"
include" lib/i.fs"
include" lib/j.fs"
include" lib/star.fs"
include" lib/star-slash.fs"
include" lib/star-slash-mod.fs"
include" lib/plus.fs"
include" lib/minus.fs"
include" lib/slash.fs"
include" lib/slash-mod.fs"
include" lib/and.fs"
include" lib/invert.fs"
include" lib/or.fs"
include" lib/u-less.fs"
include" lib/u-m-star.fs"
include" lib/u-m-slash-mod.fs"
include" lib/unloop.fs"
include" lib/xor.fs"
include" lib/zero-equal.fs"
include" lib/zero-less.fs"
include" lib/less.fs"
include" lib/two-star.fs"
include" lib/two-slash.fs"
include" lib/u-two-slash.fs"
include" lib/m-plus.fs"
include" lib/two-to-r.fs"
include" lib/two-r-fetch.fs"
include" lib/two-r-from.fs"
include" lib/n-to-r.fs"
include" lib/n-r-from.fs"
include" lib/d-plus.fs"
include" lib/d-minus.fs"
include" lib/roll.fs"
include" ../../impl/paren-semis-code.fs"
include" lib/create.fs"
include" lib/colon.fs"
include" lib/variable.fs"
include" lib/constant.fs"
include" lib/paren-does-comma.fs"
include" lib/paren-io.fs"
include" lib/user.fs"
