\ -*-forth-*-
\ MMIX machine - pure stack
\
\ lib:          code common to all MMIX pure stack models
\ ../../pure:   code common to all GAS assembly pure stack architectures
\ ../common:    code common to all MMIX models
\ ../../common: code common to all GAS assembly architectures

include" ../../pure/store.fs"
include" ../../pure/fetch.fs"
include" ../../pure/c-store.fs"
include" ../../pure/c-fetch.fs"
include" ../../pure/rp-store.fs"
include" ../../pure/sp-store.fs"
include" ../../pure/rp-fetch.fs"
include" ../../pure/sp-fetch.fs"
include" ../../pure/dash-rot.fs"
include" ../../pure/to-r.fs"
include" ../../pure/drop.fs"
include" ../../pure/dup.fs"
include" ../../pure/over.fs"
include" lib/pick.fs"
include" ../../pure/r-from.fs"
include" ../../pure/r-fetch.fs"
include" ../../pure/rot.fs"
include" ../../pure/swap.fs"
include" lib/paren-zero-branch.fs"
include" ../../common/paren-branch.fs"
include" ../../pure/paren-dolit.fs"
include" ../common/paren-s-quote.fs"
include" ../../pure/execute.fs"
include" ../../common/exit.fs"
include" lib/paren-question-do.fs"
include" lib/paren-plus-loop.fs"
include" ../../pure/paren-do.fs"
include" ../../common/paren-leave.fs"
include" lib/paren-loop.fs"
include" ../../pure/i.fs"
include" ../../pure/j.fs"
include" lib/star.fs"
include" lib/star-slash.fs"
include" lib/star-slash-mod.fs"
include" ../../pure/plus.fs"
include" ../../pure/minus.fs"
include" lib/slash.fs"
include" lib/slash-mod.fs"
include" ../../pure/and.fs"
include" ../../pure/invert.fs"
include" ../../pure/or.fs"
include" lib/u-less.fs"
include" lib/u-m-star.fs"
include" lib/u-m-slash-mod.fs"
include" ../../common/unloop.fs"
include" ../../pure/xor.fs"
include" lib/zero-equal.fs"
include" lib/zero-less.fs"
include" lib/less.fs"
include" ../../pure/two-star.fs"
include" ../../pure/two-slash.fs"
include" ../../pure/u-two-slash.fs"
include" lib/m-plus.fs"
include" ../../pure/two-to-r.fs"
include" ../../pure/two-r-fetch.fs"
include" ../../pure/two-r-from.fs"
include" lib/n-to-r.fs"
include" lib/n-r-from.fs"
include" lib/d-plus.fs"
include" lib/d-minus.fs"
include" ../../../core-ext/recursive/roll/roll.fs"
include" ../../../impl/paren-semis-code.fs"
include" ../../common/create.fs"
include" ../../common/colon.fs"
include" ../../common/variable.fs"
include" ../../common/constant.fs"
include" ../common/paren-does-comma.fs"
include" ../common/paren-io.fs"
include" ../../common/user.fs"
