include" src/32/word-size.fs"
include" src/impl/parameter/size.fs"
include" src/impl/parameter/io.fs"
include" src/gas/riscv/rv32ic/mach.fs"
include" src/impl/paren-cell.fs"
include" src/32/paren-pad.fs"
include" src/f83/sp-down/question-stack.fs"

\ BASE

include" src/search/wordlist.fs"
include" src/f83/vocabulary.fs"

vocabulary FORTH
only forth definitions

include" src/user/user.fs"
include" src/impl/paren-char-bs.fs"
include" src/impl/paren-char-rub.fs"
include" src/impl/paren-char-lf.fs"
include" src/impl/paren-char-cr.fs"
include" src/core/bl.fs"
\ include" src/impl/paren-error-abort.fs"
\ include" src/impl/paren-error-abort-quote.fs"
\ include" src/impl/paren-error-stack-o.fs"
\ include" src/impl/paren-error-stack-u.fs"
\ include" src/impl/paren-error-return-o.fs"
\ include" src/impl/paren-error-return-u.fs"
\ include" src/impl/paren-error-do.fs"
\ include" src/impl/paren-error-dict.fs"
\ include" src/impl/paren-error-mem.fs"
\ include" src/impl/paren-error-div.fs"
\ include" src/impl/paren-error-range.fs"
\ include" src/impl/paren-error-type.fs"
\ include" src/impl/paren-error-undef.fs"
\ include" src/impl/paren-error-compile-only.fs"
\ include" src/impl/paren-error-forget.fs"
\ include" src/impl/paren-error-no-name.fs"
\ include" src/impl/paren-error-num-o.fs"
\ include" src/impl/paren-error-string-o.fs"
\ include" src/impl/paren-error-def-o.fs"
\ include" src/impl/paren-error-read-only.fs"
\ include" src/impl/paren-error-unsupported.fs"
\ include" src/impl/paren-error-control.fs"
\ include" src/impl/paren-error-align.fs"
\ include" src/impl/paren-error-num.fs"
\ include" src/impl/paren-error-return-i.fs"
\ include" src/impl/paren-error-loop-u.fs"
\ include" src/impl/paren-error-recursion.fs"
\ include" src/impl/paren-error-interrupt.fs"
\ include" src/impl/paren-error-nesting.fs"
\ include" src/impl/paren-error-obsolete.fs"
\ include" src/impl/paren-error-body.fs"
\ include" src/impl/paren-error-name-a.fs"
\ include" src/impl/paren-error-blk-read.fs"
\ include" src/impl/paren-error-blk-write.fs"
\ include" src/impl/paren-error-blk-invalid.fs"
\ include" src/impl/paren-error-file-pos.fs"
\ include" src/impl/paren-error-file-io.fs"
\ include" src/impl/paren-error-file-not-found.fs"
\ include" src/impl/paren-error-eof.fs"
\ include" src/impl/paren-error-base.fs"
\ include" src/impl/paren-error-precision.fs"
\ include" src/impl/paren-error-float-div.fs"
\ include" src/impl/paren-error-float-range.fs"
\ include" src/impl/paren-error-float-stack-o.fs"
\ include" src/impl/paren-error-float-stack-u.fs"
\ include" src/impl/paren-error-float-invalid.fs"
\ include" src/impl/paren-error-deleted.fs"
\ include" src/impl/paren-error-postpone.fs"
\ include" src/impl/paren-error-search-o.fs"
\ include" src/impl/paren-error-search-u.fs"
\ include" src/impl/paren-error-changed.fs"
\ include" src/impl/paren-error-control-o.fs"
\ include" src/impl/paren-error-exception-o.fs"
\ include" src/impl/paren-error-float-o.fs"
\ include" src/impl/paren-error-float-fault.fs"
\ include" src/impl/paren-error-quit.fs"
\ include" src/impl/paren-error-char.fs"
\ include" src/impl/paren-error-fpp.fs"
\ include" src/impl/paren-error-allocate.fs"
\ include" src/impl/paren-error-free.fs"
\ include" src/impl/paren-error-resize.fs"
\ include" src/impl/paren-error-close-file.fs"
\ include" src/impl/paren-error-create-file.fs"
\ include" src/impl/paren-error-delete-file.fs"
\ include" src/impl/paren-error-file-position.fs"
\ include" src/impl/paren-error-file-size.fs"
\ include" src/impl/paren-error-file-status.fs"
\ include" src/impl/paren-error-flush-file.fs"
\ include" src/impl/paren-error-open-file.fs"
\ include" src/impl/paren-error-read-file.fs"
\ include" src/impl/paren-error-read-line.fs"
\ include" src/impl/paren-error-rename-file.fs"
\ include" src/impl/paren-error-reposition-file.fs"
\ include" src/impl/paren-error-resize-file.fs"
\ include" src/impl/paren-error-write-file.fs"
\ include" src/impl/paren-error-write-line.fs"
include" src/impl/paren-lex-start.fs"
include" src/impl/paren-lex-immediate.fs"
include" src/impl/paren-lex-compile-only.fs"
include" src/impl/paren-lex-max-name.fs"
include" src/core-ext/true.fs"
include" src/core-ext/false.fs"
include" src/fig/zero.fs"
include" src/fig/one.fs"
include" src/impl/gmpforth.fs"
include" src/impl/paren-interpret.fs"
include" src/impl/paren-respond.fs"
include" src/impl/paren-error.fs"
include" src/impl/paren-quit.fs"
include" src/impl/paren-utx-store.fs"
include" src/impl/paren-utx-question.fs"
include" src/impl/paren-urx-fetch.fs"
include" src/impl/paren-urx-question.fs"
include" src/impl/paren-reset.fs"
include" src/impl/ud-slash-mod.fs"
include" src/impl/u-t-star.fs"
include" src/impl/u-t-slash-mod.fs"
include" src/double/dabs.fs"
include" src/core/number-sign.fs"
include" src/core/number-sign-greater.fs"
include" src/core/number-sign-s.fs"
include" src/core/tick.fs"
include" src/core/paren.fs"
include" src/core/plus-store.fs"
include" src/core/plus-loop.fs"
include" src/core/comma.fs"
include" src/core/dot.fs"
include" src/core/dot-quote.fs"
include" src/core/1plus.fs"
include" src/core/1minus.fs"
include" src/core/2store.fs"
include" src/core/2fetch.fs"
include" src/core/2drop.fs"
include" src/core/2dup.fs"
include" src/core/2over.fs"
include" src/core/2swap.fs"
include" src/core/semicolon.fs"
include" src/core/less-number-sign.fs"
include" src/core/equals.fs"
include" src/core/greater-than.fs"
include" src/core/to-body.fs"
include" src/impl/toupper.fs"
include" src/fig/digit.fs"
include" src/fig/plus-minus.fs"
include" src/fig/d-plus-minus.fs"
include" src/core/to-number.fs"
include" src/core/question-dup.fs"
include" src/core/abort.fs"
include" src/impl/paren-abort-quote.fs"
include" src/core/abort-quote.fs"
include" src/core/abs.fs"
include" src/core/accept.fs"
include" src/f83/forward-mark.fs"
include" src/f83/forward-resolve.fs"
include" src/f83/backward-mark.fs"
include" src/f83/backward-resolve.fs"
include" src/tools-ext/ahead.fs"
include" src/core/align.fs"
include" src/core/aligned.fs"
include" src/core/allot.fs"
include" src/core/begin.fs"
include" src/core/c-comma.fs"
include" src/core/cell-plus.fs"
include" src/impl/cell-minus.fs"
include" src/core/cells.fs"
include" src/core/char.fs"
include" src/core/char-plus.fs"
include" src/core/chars.fs"
include" src/core/count.fs"
include" src/core/cr.fs"
include" src/impl/paren-question-name.fs"
include" src/impl/paren-create.fs"
include" src/core/decimal.fs"
include" src/core-ext/hex.fs"
include" src/double/dnegate.fs"
include" src/core/do.fs"
include" src/f83/from-name.fs"
include" src/core/does.fs"
include" src/core/else.fs"
include" src/core/emit.fs"
include" src/core/environment-query.fs"
include" src/impl/paren-paren-s-quote.fs"
include" src/impl/paren-dollar-evaluate.fs"
include" src/impl/paren-word.fs"
include" src/impl/paren-number.fs"
include" src/impl/paren-number-question.fs"
include" src/impl/number-question.fs"
include" src/impl/paren-evaluate.fs"
include" src/impl/paren-paren-evaluate.fs"
include" src/core/evaluate.fs"
include" src/core/fill.fs"
include" src/core/here.fs"
include" src/core/hold.fs"
include" src/core/if.fs"
include" src/f83/cset.fs"
include" src/f83/creset.fs"
include" src/f83/ctoggle.fs"
include" src/fig/smudge.fs"
include" src/core/immediate.fs"
include" src/impl/compile-only.fs"
include" src/core/key.fs"
include" src/core/leave.fs"
include" src/f83/question-leave.fs"
include" src/core/literal.fs"
include" src/core/loop.fs"
include" src/core/lshift.fs"
include" src/core/max.fs"
include" src/core/min.fs"
include" src/f83/bounds.fs"
include" src/string/cmove.fs"
include" src/string/cmove-up.fs"
include" src/core-ext/within.fs"
include" src/core/move.fs"
include" src/core/negate.fs"
include" src/core/postpone.fs"
include" src/core/quit.fs"
include" src/core/recurse.fs"
include" src/core/repeat.fs"
include" src/core/rshift.fs"
include" src/core/s-quote.fs"
include" src/core/s-to-d.fs"
include" src/core/sign.fs"
include" src/core/source.fs"
include" src/core/space.fs"
include" src/core/spaces.fs"
include" src/core/then.fs"
include" src/core/type.fs"
include" src/core/u-dot.fs"
include" src/core/until.fs"
include" src/core/while.fs"
include" src/core/left-bracket.fs"
include" src/core/bracket-tick.fs"
include" src/core/bracket-char.fs"
include" src/core/right-bracket.fs"
include" src/impl/paren-input.fs"
include" src/impl/paren-skip.fs"
include" src/core-ext/parse-name.fs"
include" src/core-ext/parse.fs"
include" src/core-ext/pad.fs"
include" src/core-ext/again.fs"
include" src/core-ext/question-do.fs"
include" src/impl/sgn.fs"
include" src/impl/casecompare.fs"
include" src/core/zero-not-equals.fs"
include" src/core-ext/not-equals.fs"
include" src/string/slash-string.fs"
include" src/tools-ext/cs-pick.fs"
include" src/tools-ext/cs-roll.fs"
include" src/fig/latest.fs"
include" src/core-ext/compile-comma.fs"
include" src/impl/paren-number-i.fs"
include" src/core-ext/save-input.fs"
include" src/core-ext/restore-input.fs"
include" src/f83/link-to-name.fs"
include" src/f83/name-to-link.fs"
include" src/f83/from-link.fs"
include" src/f83/to-name.fs"
include" src/impl/paren-match-name.fs"
include" src/impl/paren-search-wordlist.fs"
include" src/search/search-wordlist.fs"
include" src/search/set-current.fs"
include" src/search/definitions.fs"
include" src/core-ext/source-id.fs"
include" src/impl/paren-find.fs"
include" src/impl/query.fs"
\ include" src/core-ext/refill.fs"
include" src/impl/paren-quote-comma.fs"
include" src/exception/throw.fs"
include" src/exception/catch.fs"

\ include" src/double/m-star-slash.fs"
\ include" src/core/s-m-slash-rem.fs"
include" src/core/slash-mod.fs"
include" src/core/slash.fs"
include" src/core/star-slash-mod.fs"
include" src/core/star-slash.fs"
\ include" src/core/f-m-slash-mod.fs"
\ include" src/gas/common/trap.fs"
include" src/core/depth.fs"
include" src/tools-ext/bye.fs"
include" src/block/backslash.fs"
\ include" src/annex.fs"


\ additional words not required for basic testing
include" src/core/m-star.fs"
include" src/impl/u-t-slash.fs"
include" src/impl/u-m-star-slash.fs"
include" src/impl/u-m-slash.fs"
include" src/core/mod.fs"
include" src/core/word.fs"
include" src/core/find.fs"
include" src/double/d-dot-r.fs"
include" src/double/d-dot.fs"
include" src/core-ext/dot-r.fs"
include" src/core-ext/u-dot-r.fs"
\ .( needed for Hayes test
include" src/core-ext/dot-paren.fs"
\ include" src/core-ext/vm/colon-noname.fs"
include" src/core-ext/erase.fs"
\ include" src/core-ext/nip.fs"
\ include" src/core-ext/tuck.fs"
\ include" src/core-ext/zero-greater.fs"
include" src/tools/dot-s.fs"
include" src/tools/dump.fs"
include" src/impl/paren-name-dollar.fs"
include" src/impl/dot-name.fs"
include" src/tools/words.fs"
include" src/tools/question.fs"
\ include" src/tools-ext/code.fs"
\ include" src/tools-ext/semicolon-code.fs"
\ include" src/impl/end-code.fs"
\ include" src/f83/to-link.fs"
\ include" src/f83/body-to.fs"
\ include" src/impl/dot-wid.fs"
\ include" src/search/get-current.fs"
\ include" src/search/set-order.fs"
\ include" src/search/get-order.fs"
\ include" src/search-ext/only.fs"
\ include" src/search-ext/also.fs"
\ include" src/search-ext/order.fs"
\ include" src/search-ext/previous.fs"
include" src/impl/paren-forget-wid.fs"
include" src/impl/paren-forget.fs"
include" src/tools-ext/forget.fs"
\ include" src/core-ext/c-quote.fs"
\ include" src/impl/paren-of.fs"
\ include" src/core-ext/case.fs"
\ include" src/core-ext/of.fs"
\ include" src/core-ext/endof.fs"
\ include" src/core-ext/endcase.fs"
\ include" src/core-ext/u-greater-than.fs"
\ include" src/core-ext/buffer-colon.fs"
\ include" src/core-ext/action-of.fs"
\ include" src/core-ext/defer-fetch.fs"
\ include" src/core-ext/defer-store.fs"
\ include" src/core-ext/defer.fs"
\ include" src/core-ext/is.fs"
\ include" src/core-ext/to.fs"
\ include" src/core-ext/value.fs"
\ include" src/core-ext/bracket-compile.fs"
\ include" src/double-ext/two-value.fs"
\ include" src/facility-ext/synonym.fs"
\ include" src/impl/paren-s-backslash-quote.fs"
\ include" src/core-ext/s-backslash-quote.fs"
\ include" src/core-ext/holds.fs"
\ include" src/tools-ext/bracket-if.fs"
\ include" src/tools-ext/bracket-else.fs"
\ include" src/tools-ext/bracket-then.fs"
\ include" src/tools-ext/bracket-defined.fs"
\ include" src/tools-ext/bracket-undefined.fs"
\ include" src/impl/paren-name-to.fs"
\ include" src/tools-ext/name-to-compile.fs"
\ include" src/tools-ext/name-to-interpret.fs"
\ include" src/tools-ext/name-to-string.fs"
\ include" src/tools-ext/traverse-wordlist.fs"
\ include" src/double/2constant.fs"
\ include" src/double/2literal.fs"
\ include" src/double/2variable.fs"
\ include" src/double/d-equal.fs"
\ include" src/double/d-less.fs"
\ include" src/double/d-to-s.fs"
\ include" src/double/d-two-slash.fs"
\ include" src/double/d-two-star.fs"
\ include" src/double/d-zero-equal.fs"
\ include" src/double/d-zero-less.fs"
\ include" src/double/dmax.fs"
\ include" src/double/dmin.fs"
\ include" src/double-ext/2rot.fs"
\ include" src/double-ext/d-u-less.fs"
\ include" src/f83/convert.fs"
\ include" src/core-ext/unused.fs"
\ include" src/core-ext/marker.fs"
\ include" src/search/forth-wordlist.fs"

\ include" src/file.fs"
