#!/bin/sh
#
# run mmix forth with raw stdio
here=`dirname $0`

setting=""
# only set raw if on a tty
if tty -s
then
    setting=`stty -g`
    stty -echo raw
fi

mmix $* $here/forth.mmo

if [ z"$setting" != z ]
then
    stty "$setting"
fi

