\ -*-forth-*-
\ MMIX machine - c10 stack
\
\ lib:          code common to all MMIX c11 stack models
\ ../../c11:    code common to all GAS assembly c11 stack architectures
\ ../c10/lib:   code common to all MMIX c10 stack models
\ ../../c10:    code common to all GAS assembly c10 stack architectures
\ ../common:    code common to all MMIX models
\ ../../common: code common to all GAS assembly architectures

include" ../../c10/store.fs"
include" ../../c10/fetch.fs"
include" ../../c10/c-store.fs"
include" ../../c10/c-fetch.fs"
include" ../../c11/rp-store.fs"
include" ../../c10/sp-store.fs"
include" ../../c10/rp-fetch.fs"
include" ../../c10/sp-fetch.fs"
include" ../../c10/dash-rot.fs"
include" ../../c11/to-r.fs"
include" ../../c10/drop.fs"
include" ../../c10/dup.fs"
include" ../../c10/over.fs"
include" ../c10/lib/pick.fs"
include" ../../c11/r-from.fs"
include" ../../c11/r-fetch.fs"
include" ../../c10/rot.fs"
include" ../../c10/swap.fs"
include" ../c10/lib/paren-zero-branch.fs"
include" ../../common/paren-branch.fs"
include" ../../c10/paren-dolit.fs"
include" ../c10/lib/paren-s-quote.fs"
include" ../../c10/execute.fs"
include" ../../common/exit.fs"
include" lib/paren-question-do.fs"
include" lib/paren-plus-loop.fs"
include" ../../c11/paren-do.fs"
include" ../../c11/paren-leave.fs"
include" lib/paren-loop.fs"
include" ../../c11/i.fs"
include" ../../c10/j.fs"
include" ../c10/lib/star.fs"
include" ../c10/lib/star-slash.fs"
include" ../c10/lib/star-slash-mod.fs"
include" ../../c10/plus.fs"
include" ../../c10/minus.fs"
include" ../c10/lib/slash.fs"
include" ../c10/lib/slash-mod.fs"
include" ../../c10/and.fs"
include" ../../c10/invert.fs"
include" ../../c10/or.fs"
include" ../c10/lib/u-less.fs"
include" ../c10/lib/u-m-star.fs"
include" ../c10/lib/u-m-slash-mod.fs"
include" ../../c11/unloop.fs"
include" ../../c10/xor.fs"
include" ../c10/lib/zero-equal.fs"
include" ../c10/lib/zero-less.fs"
include" ../c10/lib/less.fs"
include" ../../c10/two-star.fs"
include" ../../c10/two-slash.fs"
include" ../../c10/u-two-slash.fs"
include" ../c10/lib/m-plus.fs"
include" ../../c11/two-to-r.fs"
include" ../../c11/two-r-fetch.fs"
include" ../../c11/two-r-from.fs"
include" lib/n-to-r.fs"
include" lib/n-r-from.fs"
include" ../c10/lib/d-plus.fs"
include" ../c10/lib/d-minus.fs"
include" ../../../core-ext/recursive/roll/roll.fs"
include" ../../../impl/paren-semis-code.fs"
include" ../../common/create.fs"
include" ../../common/colon.fs"
include" ../../common/variable.fs"
include" ../../common/constant.fs"
include" ../common/paren-does-comma.fs"
include" ../c10/lib/paren-io.fs"
include" ../../common/user.fs"
