name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: |
        sudo apt-get update
        sudo apt-get install gcc-multilib:i386
        ls /usr/include/asm
        head  /usr/include/asm/unistd.h
    - name: make
      run: make
    - name: make check
      run: make check TEST_ARG=-v
